# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'name_new_user.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_name_new_user(object):
    def setupUi(self, name_new_user):
        name_new_user.setObjectName("name_new_user")
        name_new_user.resize(1186, 706)
        name_new_user.setStyleSheet("background-image: url(\'a.jpg\');")
        self.centralwidget = QtWidgets.QWidget(name_new_user)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.backtomanagedrivers_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.backtomanagedrivers_button.sizePolicy().hasHeightForWidth())
        self.backtomanagedrivers_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.backtomanagedrivers_button.setFont(font)
        self.backtomanagedrivers_button.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.backtomanagedrivers_button.setObjectName("backtomanagedrivers_button")
        self.verticalLayout.addWidget(self.backtomanagedrivers_button)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(150)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: Black;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b1.sizePolicy().hasHeightForWidth())
        self.b1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b1.setFont(font)
        self.b1.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.b1.setObjectName("b1")
        self.horizontalLayout.addWidget(self.b1)
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b2.sizePolicy().hasHeightForWidth())
        self.b2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.b2.setObjectName("b2")
        self.horizontalLayout.addWidget(self.b2)
        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b3.sizePolicy().hasHeightForWidth())
        self.b3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b3.setFont(font)
        self.b3.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.b3.setObjectName("b3")
        self.horizontalLayout.addWidget(self.b3)
        self.b4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b4.sizePolicy().hasHeightForWidth())
        self.b4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b4.setFont(font)
        self.b4.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.b4.setObjectName("b4")
        self.horizontalLayout.addWidget(self.b4)
        self.b5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b5.sizePolicy().hasHeightForWidth())
        self.b5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b5.setFont(font)
        self.b5.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.b5.setObjectName("b5")
        self.horizontalLayout.addWidget(self.b5)
        self.b6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b6.sizePolicy().hasHeightForWidth())
        self.b6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b6.setFont(font)
        self.b6.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.b6.setObjectName("b6")
        self.horizontalLayout.addWidget(self.b6)
        self.b7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b7.sizePolicy().hasHeightForWidth())
        self.b7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b7.setFont(font)
        self.b7.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.b7.setObjectName("b7")
        self.horizontalLayout.addWidget(self.b7)
        self.b8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b8.sizePolicy().hasHeightForWidth())
        self.b8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b8.setFont(font)
        self.b8.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.b8.setObjectName("b8")
        self.horizontalLayout.addWidget(self.b8)
        self.b9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b9.sizePolicy().hasHeightForWidth())
        self.b9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b9.setFont(font)
        self.b9.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.b9.setObjectName("b9")
        self.horizontalLayout.addWidget(self.b9)
        self.b0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b0.sizePolicy().hasHeightForWidth())
        self.b0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.b0.setFont(font)
        self.b0.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.b0.setObjectName("b0")
        self.horizontalLayout.addWidget(self.b0)
        self.bback = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bback.sizePolicy().hasHeightForWidth())
        self.bback.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bback.setFont(font)
        self.bback.setStyleSheet("color: white;\n"
"border: 3px solid yellow;")
        self.bback.setObjectName("bback")
        self.horizontalLayout.addWidget(self.bback)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bq = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bq.sizePolicy().hasHeightForWidth())
        self.bq.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bq.setFont(font)
        self.bq.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bq.setObjectName("bq")
        self.horizontalLayout_2.addWidget(self.bq)
        self.bw = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bw.sizePolicy().hasHeightForWidth())
        self.bw.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bw.setFont(font)
        self.bw.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bw.setObjectName("bw")
        self.horizontalLayout_2.addWidget(self.bw)
        self.be = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.be.sizePolicy().hasHeightForWidth())
        self.be.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.be.setFont(font)
        self.be.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.be.setObjectName("be")
        self.horizontalLayout_2.addWidget(self.be)
        self.br = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.br.sizePolicy().hasHeightForWidth())
        self.br.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.br.setFont(font)
        self.br.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.br.setObjectName("br")
        self.horizontalLayout_2.addWidget(self.br)
        self.bt = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt.sizePolicy().hasHeightForWidth())
        self.bt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bt.setFont(font)
        self.bt.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bt.setObjectName("bt")
        self.horizontalLayout_2.addWidget(self.bt)
        self.by = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.by.sizePolicy().hasHeightForWidth())
        self.by.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.by.setFont(font)
        self.by.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.by.setObjectName("by")
        self.horizontalLayout_2.addWidget(self.by)
        self.bu = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bu.sizePolicy().hasHeightForWidth())
        self.bu.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bu.setFont(font)
        self.bu.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bu.setObjectName("bu")
        self.horizontalLayout_2.addWidget(self.bu)
        self.bi = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bi.sizePolicy().hasHeightForWidth())
        self.bi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bi.setFont(font)
        self.bi.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bi.setObjectName("bi")
        self.horizontalLayout_2.addWidget(self.bi)
        self.bo = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bo.sizePolicy().hasHeightForWidth())
        self.bo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bo.setFont(font)
        self.bo.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bo.setObjectName("bo")
        self.horizontalLayout_2.addWidget(self.bo)
        self.bp = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bp.sizePolicy().hasHeightForWidth())
        self.bp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bp.setFont(font)
        self.bp.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bp.setObjectName("bp")
        self.horizontalLayout_2.addWidget(self.bp)
        self.benter = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.benter.sizePolicy().hasHeightForWidth())
        self.benter.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.benter.setFont(font)
        self.benter.setStyleSheet("color: white;\n"
"border: 3px solid yellow;")
        self.benter.setObjectName("benter")
        self.horizontalLayout_2.addWidget(self.benter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ba = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ba.sizePolicy().hasHeightForWidth())
        self.ba.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.ba.setFont(font)
        self.ba.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.ba.setObjectName("ba")
        self.horizontalLayout_4.addWidget(self.ba)
        self.bs = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bs.sizePolicy().hasHeightForWidth())
        self.bs.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bs.setFont(font)
        self.bs.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bs.setObjectName("bs")
        self.horizontalLayout_4.addWidget(self.bs)
        self.bd = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bd.sizePolicy().hasHeightForWidth())
        self.bd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bd.setFont(font)
        self.bd.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bd.setObjectName("bd")
        self.horizontalLayout_4.addWidget(self.bd)
        self.bf = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bf.sizePolicy().hasHeightForWidth())
        self.bf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bf.setFont(font)
        self.bf.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bf.setObjectName("bf")
        self.horizontalLayout_4.addWidget(self.bf)
        self.bg = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bg.sizePolicy().hasHeightForWidth())
        self.bg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bg.setFont(font)
        self.bg.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bg.setObjectName("bg")
        self.horizontalLayout_4.addWidget(self.bg)
        self.bh = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bh.sizePolicy().hasHeightForWidth())
        self.bh.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bh.setFont(font)
        self.bh.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bh.setObjectName("bh")
        self.horizontalLayout_4.addWidget(self.bh)
        self.bj = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bj.sizePolicy().hasHeightForWidth())
        self.bj.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bj.setFont(font)
        self.bj.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bj.setObjectName("bj")
        self.horizontalLayout_4.addWidget(self.bj)
        self.bk = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bk.sizePolicy().hasHeightForWidth())
        self.bk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bk.setFont(font)
        self.bk.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bk.setObjectName("bk")
        self.horizontalLayout_4.addWidget(self.bk)
        self.bl = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bl.sizePolicy().hasHeightForWidth())
        self.bl.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bl.setFont(font)
        self.bl.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bl.setObjectName("bl")
        self.horizontalLayout_4.addWidget(self.bl)
        self.bcap = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bcap.sizePolicy().hasHeightForWidth())
        self.bcap.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bcap.setFont(font)
        self.bcap.setStyleSheet("color: white;\n"
"border: 3px solid yellow;")
        self.bcap.setObjectName("bcap")
        self.horizontalLayout_4.addWidget(self.bcap)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bz = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bz.sizePolicy().hasHeightForWidth())
        self.bz.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bz.setFont(font)
        self.bz.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bz.setObjectName("bz")
        self.horizontalLayout_5.addWidget(self.bz)
        self.bx = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bx.sizePolicy().hasHeightForWidth())
        self.bx.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bx.setFont(font)
        self.bx.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bx.setObjectName("bx")
        self.horizontalLayout_5.addWidget(self.bx)
        self.bc = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bc.sizePolicy().hasHeightForWidth())
        self.bc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bc.setFont(font)
        self.bc.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bc.setObjectName("bc")
        self.horizontalLayout_5.addWidget(self.bc)
        self.bv = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bv.sizePolicy().hasHeightForWidth())
        self.bv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bv.setFont(font)
        self.bv.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bv.setObjectName("bv")
        self.horizontalLayout_5.addWidget(self.bv)
        self.bb = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bb.sizePolicy().hasHeightForWidth())
        self.bb.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bb.setFont(font)
        self.bb.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bb.setObjectName("bb")
        self.horizontalLayout_5.addWidget(self.bb)
        self.bn = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bn.sizePolicy().hasHeightForWidth())
        self.bn.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bn.setFont(font)
        self.bn.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bn.setObjectName("bn")
        self.horizontalLayout_5.addWidget(self.bn)
        self.bm = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bm.sizePolicy().hasHeightForWidth())
        self.bm.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bm.setFont(font)
        self.bm.setStyleSheet("color: white;\n"
"border: 3px solid red;")
        self.bm.setObjectName("bm")
        self.horizontalLayout_5.addWidget(self.bm)
        self.bspace = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bspace.sizePolicy().hasHeightForWidth())
        self.bspace.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.bspace.setFont(font)
        self.bspace.setStyleSheet("color: white;\n"
"border: 3px solid yellow;")
        self.bspace.setObjectName("bspace")
        self.horizontalLayout_5.addWidget(self.bspace)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(3, 1)
        self.horizontalLayout_5.setStretch(4, 1)
        self.horizontalLayout_5.setStretch(5, 1)
        self.horizontalLayout_5.setStretch(6, 1)
        self.horizontalLayout_5.setStretch(7, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 5)
        self.verticalLayout.setStretch(3, 3)
        self.verticalLayout.setStretch(4, 3)
        self.verticalLayout.setStretch(5, 3)
        self.verticalLayout.setStretch(6, 3)
        name_new_user.setCentralWidget(self.centralwidget)

        self.retranslateUi(name_new_user)
        QtCore.QMetaObject.connectSlotsByName(name_new_user)

    def retranslateUi(self, name_new_user):
        _translate = QtCore.QCoreApplication.translate
        name_new_user.setWindowTitle(_translate("name_new_user", "name_new_user"))
        self.backtomanagedrivers_button.setText(_translate("name_new_user", "Back to Mange Drivers"))
        self.label.setText(_translate("name_new_user", "Add a New Driver\'s Name"))
        self.b1.setText(_translate("name_new_user", "1"))
        self.b2.setText(_translate("name_new_user", "2"))
        self.b3.setText(_translate("name_new_user", "3"))
        self.b4.setText(_translate("name_new_user", "4"))
        self.b5.setText(_translate("name_new_user", "5"))
        self.b6.setText(_translate("name_new_user", "6"))
        self.b7.setText(_translate("name_new_user", "7"))
        self.b8.setText(_translate("name_new_user", "8"))
        self.b9.setText(_translate("name_new_user", "9"))
        self.b0.setText(_translate("name_new_user", "0"))
        self.bback.setText(_translate("name_new_user", "Back"))
        self.bq.setText(_translate("name_new_user", "q"))
        self.bw.setText(_translate("name_new_user", "w"))
        self.be.setText(_translate("name_new_user", "e"))
        self.br.setText(_translate("name_new_user", "r"))
        self.bt.setText(_translate("name_new_user", "t"))
        self.by.setText(_translate("name_new_user", "y"))
        self.bu.setText(_translate("name_new_user", "u"))
        self.bi.setText(_translate("name_new_user", "i"))
        self.bo.setText(_translate("name_new_user", "o"))
        self.bp.setText(_translate("name_new_user", "p"))
        self.benter.setText(_translate("name_new_user", "Enter"))
        self.ba.setText(_translate("name_new_user", "a"))
        self.bs.setText(_translate("name_new_user", "s"))
        self.bd.setText(_translate("name_new_user", "d"))
        self.bf.setText(_translate("name_new_user", "f"))
        self.bg.setText(_translate("name_new_user", "g"))
        self.bh.setText(_translate("name_new_user", "h"))
        self.bj.setText(_translate("name_new_user", "j"))
        self.bk.setText(_translate("name_new_user", "k"))
        self.bl.setText(_translate("name_new_user", "l"))
        self.bcap.setText(_translate("name_new_user", "Caps"))
        self.bz.setText(_translate("name_new_user", "z"))
        self.bx.setText(_translate("name_new_user", "x"))
        self.bc.setText(_translate("name_new_user", "c"))
        self.bv.setText(_translate("name_new_user", "v"))
        self.bb.setText(_translate("name_new_user", "b"))
        self.bn.setText(_translate("name_new_user", "n"))
        self.bm.setText(_translate("name_new_user", "m"))
        self.bspace.setText(_translate("name_new_user", "Space"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    name_new_user = QtWidgets.QMainWindow()
    ui = Ui_name_new_user()
    ui.setupUi(name_new_user)
    name_new_user.show()
    sys.exit(app.exec_())

