# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'review_footage.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_review_footage(object):
    def setupUi(self, review_footage):
        review_footage.setObjectName("review_footage")
        review_footage.resize(1212, 765)
        review_footage.setStyleSheet(" background-image: url(\'a.jpg\');\n"
"")
        self.centralwidget = QtWidgets.QWidget(review_footage)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.back_to_root = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_to_root.sizePolicy().hasHeightForWidth())
        self.back_to_root.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.back_to_root.setFont(font)
        self.back_to_root.setStyleSheet("color:white;\n"
"border: 3px solid red;")
        self.back_to_root.setObjectName("back_to_root")
        self.horizontalLayout.addWidget(self.back_to_root)
        self.rescan = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rescan.sizePolicy().hasHeightForWidth())
        self.rescan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.rescan.setFont(font)
        self.rescan.setStyleSheet("color:white;\n"
"border: 3px solid red;")
        self.rescan.setObjectName("rescan")
        self.horizontalLayout.addWidget(self.rescan)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tab = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.tab.setFont(font)
        self.tab.setStyleSheet("border: 1px solid red;")
        self.tab.setIconSize(QtCore.QSize(16, 16))
        self.tab.setObjectName("tab")
        self.camera_left = QtWidgets.QWidget()
        self.camera_left.setObjectName("camera_left")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.camera_left)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.list_left = QtWidgets.QListView(self.camera_left)
        self.list_left.setStyleSheet("QListView{background-color: black; color: white ;font-size: 24px; outline:none;font-weight:bold}\n"
"QScrollBar:vertical {\n"
"width: 60px;\n"
"}")
        self.list_left.setObjectName("list_left")
        self.horizontalLayout_2.addWidget(self.list_left)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.play_left = QtWidgets.QPushButton(self.camera_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_left.sizePolicy().hasHeightForWidth())
        self.play_left.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.play_left.setFont(font)
        self.play_left.setStyleSheet("color:white;\n"
"border: 3px solid red;")
        self.play_left.setObjectName("play_left")
        self.verticalLayout_2.addWidget(self.play_left)
        self.delete_left = QtWidgets.QPushButton(self.camera_left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_left.sizePolicy().hasHeightForWidth())
        self.delete_left.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.delete_left.setFont(font)
        self.delete_left.setStyleSheet("color:white;\n"
"border: 3px solid red;")
        self.delete_left.setObjectName("delete_left")
        self.verticalLayout_2.addWidget(self.delete_left)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 1)
        self.tab.addTab(self.camera_left, "")
        self.camera_right = QtWidgets.QWidget()
        self.camera_right.setObjectName("camera_right")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.camera_right)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.list_right = QtWidgets.QListView(self.camera_right)
        self.list_right.setStyleSheet("QListView{background-color: black; color: white ;font-size: 24px; outline:none;font-weight:bold}\n"
"QScrollBar:vertical {\n"
"width: 60px;\n"
"}")
        self.list_right.setObjectName("list_right")
        self.horizontalLayout_4.addWidget(self.list_right)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.play_right = QtWidgets.QPushButton(self.camera_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_right.sizePolicy().hasHeightForWidth())
        self.play_right.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.play_right.setFont(font)
        self.play_right.setStyleSheet("color:white;\n"
"border: 3px solid red;")
        self.play_right.setObjectName("play_right")
        self.verticalLayout_4.addWidget(self.play_right)
        self.delete_right = QtWidgets.QPushButton(self.camera_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_right.sizePolicy().hasHeightForWidth())
        self.delete_right.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.delete_right.setFont(font)
        self.delete_right.setStyleSheet("color:white;\n"
"border: 3px solid red;")
        self.delete_right.setObjectName("delete_right")
        self.verticalLayout_4.addWidget(self.delete_right)
        self.horizontalLayout_4.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 1)
        self.tab.addTab(self.camera_right, "")
        self.camera_front = QtWidgets.QWidget()
        self.camera_front.setObjectName("camera_front")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.camera_front)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.list_front = QtWidgets.QListView(self.camera_front)
        self.list_front.setStyleSheet("QListView{background-color: black; color: white ;font-size: 24px; outline:none;font-weight:bold}\n"
"QScrollBar:vertical {\n"
"width: 60px;\n"
"}")
        self.list_front.setObjectName("list_front")
        self.horizontalLayout_5.addWidget(self.list_front)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.play_front = QtWidgets.QPushButton(self.camera_front)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_front.sizePolicy().hasHeightForWidth())
        self.play_front.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.play_front.setFont(font)
        self.play_front.setStyleSheet("color:white;\n"
"border: 3px solid red;")
        self.play_front.setObjectName("play_front")
        self.verticalLayout_5.addWidget(self.play_front)
        self.delete_front = QtWidgets.QPushButton(self.camera_front)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_front.sizePolicy().hasHeightForWidth())
        self.delete_front.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.delete_front.setFont(font)
        self.delete_front.setStyleSheet("color:white;\n"
"border: 3px solid red;")
        self.delete_front.setObjectName("delete_front")
        self.verticalLayout_5.addWidget(self.delete_front)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5.setStretch(0, 5)
        self.horizontalLayout_5.setStretch(1, 1)
        self.tab.addTab(self.camera_front, "")
        self.camera_back = QtWidgets.QWidget()
        self.camera_back.setObjectName("camera_back")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.camera_back)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.list_back = QtWidgets.QListView(self.camera_back)
        self.list_back.setStyleSheet("QListView{background-color: black; color: white ;font-size: 24px; outline:none;font-weight:bold}\n"
"QScrollBar:vertical {\n"
"width: 60px;\n"
"}")
        self.list_back.setObjectName("list_back")
        self.horizontalLayout_6.addWidget(self.list_back)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.play_back = QtWidgets.QPushButton(self.camera_back)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.play_back.sizePolicy().hasHeightForWidth())
        self.play_back.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.play_back.setFont(font)
        self.play_back.setStyleSheet("color:white;\n"
"border: 3px solid red;")
        self.play_back.setObjectName("play_back")
        self.verticalLayout_6.addWidget(self.play_back)
        self.delete_back = QtWidgets.QPushButton(self.camera_back)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delete_back.sizePolicy().hasHeightForWidth())
        self.delete_back.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.delete_back.setFont(font)
        self.delete_back.setStyleSheet("color:white;\n"
"border: 3px solid red;")
        self.delete_back.setObjectName("delete_back")
        self.verticalLayout_6.addWidget(self.delete_back)
        self.horizontalLayout_6.addLayout(self.verticalLayout_6)
        self.horizontalLayout_6.setStretch(0, 5)
        self.horizontalLayout_6.setStretch(1, 1)
        self.tab.addTab(self.camera_back, "")
        self.verticalLayout.addWidget(self.tab)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 5)
        review_footage.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(review_footage)
        self.statusbar.setObjectName("statusbar")
        review_footage.setStatusBar(self.statusbar)

        self.retranslateUi(review_footage)
        self.tab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(review_footage)

    def retranslateUi(self, review_footage):
        _translate = QtCore.QCoreApplication.translate
        review_footage.setWindowTitle(_translate("review_footage", "review_footage"))
        self.back_to_root.setText(_translate("review_footage", "Back to RootMenu"))
        self.rescan.setText(_translate("review_footage", "Rescan"))
        self.play_left.setText(_translate("review_footage", "Play"))
        self.delete_left.setText(_translate("review_footage", "Delete"))
        self.tab.setTabText(self.tab.indexOf(self.camera_left), _translate("review_footage", "Left"))
        self.play_right.setText(_translate("review_footage", "Play"))
        self.delete_right.setText(_translate("review_footage", "Delete"))
        self.tab.setTabText(self.tab.indexOf(self.camera_right), _translate("review_footage", "Right"))
        self.play_front.setText(_translate("review_footage", "Play"))
        self.delete_front.setText(_translate("review_footage", "Delete"))
        self.tab.setTabText(self.tab.indexOf(self.camera_front), _translate("review_footage", "Front"))
        self.play_back.setText(_translate("review_footage", "Play"))
        self.delete_back.setText(_translate("review_footage", "Delete"))
        self.tab.setTabText(self.tab.indexOf(self.camera_back), _translate("review_footage", "Back"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    review_footage = QtWidgets.QMainWindow()
    ui = Ui_review_footage()
    ui.setupUi(review_footage)
    review_footage.show()
    sys.exit(app.exec_())
